/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * Learn more about Gradle by exploring our Samples at https://docs.gradle.org/9.2.1/samples
 */

plugins {
    java
    application
}
repositories {
    mavenCentral()
}

dependencies {
    implementation("net.dv8tion:JDA:6.2.0")
    implementation("org.jsoup:jsoup:1.21.2")
}

java {
    toolchain {
        languageVersion.set(JavaLanguageVersion.of(17))
    }
}

application {
    mainClass.set("com.dragoncon_reminder.bot.Bot")
}

tasks.withType<JavaCompile> {
    options.encoding = "UTF-8"
}