/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * Learn more about Gradle by exploring our Samples at https://docs.gradle.org/9.2.1/samples
 */

plugins {
    java
    application
}
repositories {
    mavenCentral()
}

dependencies {
    // Guava library for @VisibleForTesting annotation
    implementation("com.google.guava:guava:33.5.0-jre")
    implementation("net.dv8tion:JDA:6.2.0")
    implementation("org.jsoup:jsoup:1.21.2")
    runtimeOnly("ch.qos.logback:logback-classic:1.5.6") // Use 1.3.x for Java 8

    // JUnit 5 dependencies
    testImplementation("org.mockito:mockito-core:5.+")
    testImplementation("org.junit.jupiter:junit-jupiter-api:5.11.0-M1")
    testRuntimeOnly("org.junit.jupiter:junit-jupiter-engine:5.11.0-M1")
    testRuntimeOnly("org.junit.platform:junit-platform-launcher")

    // Mockito for mocking
    testImplementation("org.mockito:mockito-core:5.14.2")
    testImplementation("org.mockito:mockito-junit-jupiter:5.14.2")
}

// Configure the test task to use the JUnit Platform (for JUnit 5)
tasks.test {
    useJUnitPlatform()
}

java {
    toolchain {
        languageVersion.set(JavaLanguageVersion.of(17))
    }
}

application {
    mainClass.set("com.dragoncon_reminder.bot.Bot")
}

tasks.withType<JavaCompile> {
    options.encoding = "UTF-8"
}

// Create a fat JAR with all dependencies
tasks.jar {
    manifest {
        attributes["Main-Class"] = "com.dragoncon_reminder.bot.Bot"
    }
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
    from(configurations.runtimeClasspath.get().map { if (it.isDirectory) it else zipTree(it) })
}