/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * Learn more about Gradle by exploring our Samples at https://docs.gradle.org/9.2.1/samples
 */

plugins {
    java
    application
}
repositories {
    mavenCentral()
}

dependencies {
    implementation("net.dv8tion:JDA:6.2.0")
    implementation("org.jsoup:jsoup:1.21.2")

    // OR, for explicit JUnit 5 dependencies (recommended for full JUnit 5 features)
    testImplementation("org.junit.jupiter:junit-jupiter-api:5.11.0-M1") // Use the latest version
    testRuntimeOnly("org.junit.jupiter:junit-jupiter-engine:5.11.0-M1") // Use the latest version
    testRuntimeOnly("org.junit.platform:junit-platform-launcher") // Use the latest version
}

// Configure the test task to use the JUnit Platform (for JUnit 5)
tasks.test {
    useJUnitPlatform()
}

java {
    toolchain {
        languageVersion.set(JavaLanguageVersion.of(17))
    }
}

application {
    mainClass.set("com.dragoncon_reminder.bot.Bot")
}

tasks.withType<JavaCompile> {
    options.encoding = "UTF-8"
}